# Generated by Django 3.0.6 on 2020-12-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='data',
            field=models.TextField(blank=True),
        ),
    ]
