# Generated by Django 3.0.6 on 2020-12-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strata', '0002_character_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='character_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='character',
            name='advantage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='disadvantage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='race',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='character',
            name='shock',
            field=models.IntegerField(default=0),
        ),
    ]
