# Generated by Django 3.0.6 on 2020-12-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strata', '0003_auto_20201208_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='data',
            field=models.BinaryField(blank=True),
        ),
    ]
